# Copyright 2018 Google LLC
# Copyright 2018-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0

licenses(["notice"])  # Apache v2

package(
    default_visibility = ["//visibility:public"],
)

filegroup(
    name = "stratum_models",
    srcs = [
        "stratum.yang",
    ],
)
