# Copyright 2021-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0

FROM bitnami/minideb:stretch as runtime

LABEL maintainer="Stratum dev <stratum-dev@lists.stratumproject.org>"
LABEL description="Docker-based distribution of the Stratum-tools package"

ADD ./stratum_tools_deb.deb /
RUN install_packages ./stratum_tools_deb.deb
RUN rm ./stratum_tools_deb.deb

ENTRYPOINT ["bash"]
CMD ["ls -l /usr/local/bin"]
