#
# Copyright 2018-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM stratumproject/build:build

ARG USER_NAME=default
ARG USER_ID=1000
ARG GIT_GLOBAL_NAME=
ARG GIT_GLOBAL_EMAIL=
ARG GIT_GLOBAL_EDITOR=vim

RUN useradd -ms /bin/bash -l -u $USER_ID $USER_NAME && \
    adduser $USER_NAME sudo && \
    echo "%sudo ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers && \
    echo "source /usr/local/lib/bazel/bin/bazel-complete.bash" >> /home/$USER_NAME/.bashrc

USER $USER_NAME

RUN (test "$GIT_GLOBAL_NAME" = "" || git config --global user.name "$GIT_GLOBAL_NAME") && \
    (test "$GIT_GLOBAL_EMAIL" = "" || git config --global user.email "$GIT_GLOBAL_EMAIL") && \
    (test "$GIT_GLOBAL_EDITOR" = "" || git config --global code.editor "$GIT_GLOBAL_EDITOR")
