FROM stratumproject/build:bazel-0.23.2

ENV JDK_URL https://mirror.bazel.build/openjdk/azul-zulu11.29.3-ca-jdk11.0.2/zulu11.29.3-ca-jdk11.0.2-linux_x64.tar.gz
ENV JAVA_HOME /usr/local/lib/jvm
ENV PATH=$PATH:/usr/local/lib/jvm/bin

# Install java and lcov for Bazel coverage
RUN wget $JDK_URL -O $HOME/jdk_11.0.2.tar.gz && \
    mkdir -p $JAVA_HOME && \
    tar xf $HOME/jdk_11.0.2.tar.gz -C $JAVA_HOME --strip-components=1 && \
    apt install -y lcov curl && \
    rm $HOME/jdk_11.0.2.tar.gz
