
# Copyright 2021-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0

package(
    default_visibility = ["//visibility:public"],
)

# TODO explain this

exports_files(glob(["LICENSE*", "NOTICE*"]))