package(
    default_visibility = ["//visibility:public"],
)

# FIXME: Wait until python support
# py_binary(
#     name = "gnmi-cli",
#     srcs = ["gnmi-cli.py"],
#     deps = ["@com_github_openconfig_gnmi//:gnmi_proto_py"]
# )