load(
    "//bazel:rules.bzl",
    "STRATUM_INTERNAL",
)

licenses(["notice"])  # Apache v2

filegroup(
    name = "yext_proto_srcs",
    srcs = ["yext.proto"],
    visibility = STRATUM_INTERNAL,
)

filegroup(
    name = "ywrapper_proto_srcs",
    srcs = ["ywrappers.proto"],
    visibility = STRATUM_INTERNAL,
)

filegroup(
    name = "openconfig_proto_srcs",
    srcs = ["openconfig.proto"],
    visibility = STRATUM_INTERNAL,
)

filegroup(
    name = "openconfig_google_bcm_proto_srcs",
    srcs = ["openconfig_google_bcm.proto"],
    visibility = STRATUM_INTERNAL,
)
