load(
    "//platforms/networking/sandblaze/portage:build_defs.bzl",
    "SANDBLAZE_INTERNAL",
)

filegroup(
    name = "yext_proto_srcs",
    srcs = ["yext.proto"],
    visibility = SANDBLAZE_INTERNAL,
)

filegroup(
    name = "ywrapper_proto_srcs",
    srcs = ["ywrappers.proto"],
    visibility = SANDBLAZE_INTERNAL,
)

filegroup(
    name = "openconfig_proto_srcs",
    srcs = ["openconfig.proto"],
    visibility = SANDBLAZE_INTERNAL,
)

filegroup(
    name = "openconfig_google_bcm_proto_srcs",
    srcs = ["openconfig_google_bcm.proto"],
    visibility = SANDBLAZE_INTERNAL,
)
