#!/bin/bash
# Copyright 2020-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0

set -ex

# Files in this branch that are different from main.
CHANGED_FILES=$(git diff --name-only --diff-filter=d origin/main -- '*.h' '*.cc')

# All proto files.
PROTO_FILES=$(git ls-files "*.proto")

# All header files.
HEADER_FILES=$(git ls-files "*.h")

# List of files that are already formatted.
read -r -d '\0' KNOWN_FILES << EOF
stratum/glue/gtl/map_util_test.cc
stratum/glue/logging.cc
stratum/glue/net_util/absl_test.cc
stratum/glue/net_util/bits_test.cc
stratum/glue/net_util/bits.cc
stratum/glue/net_util/ipaddress_test.cc
stratum/glue/net_util/ipaddress.cc
stratum/glue/net_util/ports.cc
stratum/glue/stamping.cc
stratum/glue/status/canonical_errors.cc
stratum/glue/status/posix_error_space_test.cc
stratum/glue/status/posix_error_space.cc
stratum/glue/status/status_macros.cc
stratum/glue/status/status_test_util_test.cc
stratum/glue/status/status_test_util.cc
stratum/glue/status/status_test.cc
stratum/glue/status/status.cc
stratum/glue/status/statusor_test.cc
stratum/glue/status/statusor.cc
stratum/hal/bin/barefoot/bf_pipeline_builder.cc
stratum/hal/bin/barefoot/main_bfrt.cc
stratum/hal/bin/barefoot/main.cc
stratum/hal/bin/bcm/sim/main.cc
stratum/hal/bin/bcm/standalone/main.cc
stratum/hal/bin/bmv2/main.cc
stratum/hal/bin/dummy/dummy_cli.cc
stratum/hal/bin/dummy/main.cc
stratum/hal/bin/np4intel/main.cc
stratum/hal/config/chassis_config_migrator.cc
stratum/hal/config/config_validator_main.cc
stratum/hal/lib/barefoot/bf_chassis_manager_test.cc
stratum/hal/lib/barefoot/bf_chassis_manager.cc
stratum/hal/lib/barefoot/bf_pipeline_utils_test.cc
stratum/hal/lib/barefoot/bf_pipeline_utils.cc
stratum/hal/lib/barefoot/bf_sde_wrapper.cc
stratum/hal/lib/barefoot/bf_switch.cc
stratum/hal/lib/barefoot/bfrt_counter_manager_test.cc
stratum/hal/lib/barefoot/bfrt_counter_manager.cc
stratum/hal/lib/barefoot/bfrt_id_mapper.cc
stratum/hal/lib/barefoot/bfrt_node_test.cc
stratum/hal/lib/barefoot/bfrt_node.cc
stratum/hal/lib/barefoot/bfrt_packetio_manager_test.cc
stratum/hal/lib/barefoot/bfrt_packetio_manager.cc
stratum/hal/lib/barefoot/bfrt_pre_manager_test.cc
stratum/hal/lib/barefoot/bfrt_pre_manager.cc
stratum/hal/lib/barefoot/bfrt_switch_test.cc
stratum/hal/lib/barefoot/bfrt_switch.cc
stratum/hal/lib/barefoot/bfrt_table_manager_test.cc
stratum/hal/lib/barefoot/bfrt_table_manager.cc
stratum/hal/lib/barefoot/test_main.cc
stratum/hal/lib/barefoot/utils_test.cc
stratum/hal/lib/barefoot/utils.cc
stratum/hal/lib/bcm/acl_table_test.cc
stratum/hal/lib/bcm/acl_table.cc
stratum/hal/lib/bcm/bcm_acl_manager.cc
stratum/hal/lib/bcm/bcm_chassis_manager_test.cc
stratum/hal/lib/bcm/bcm_chassis_manager.cc
stratum/hal/lib/bcm/bcm_flow_table_test.cc
stratum/hal/lib/bcm/bcm_global_vars.cc
stratum/hal/lib/bcm/bcm_l2_manager_test.cc
stratum/hal/lib/bcm/bcm_l2_manager.cc
stratum/hal/lib/bcm/bcm_l3_manager_test.cc
stratum/hal/lib/bcm/bcm_l3_manager.cc
stratum/hal/lib/bcm/bcm_node_test.cc
stratum/hal/lib/bcm/bcm_node.cc
stratum/hal/lib/bcm/bcm_packetio_manager_test.cc
stratum/hal/lib/bcm/bcm_packetio_manager.cc
stratum/hal/lib/bcm/bcm_sdk_sim.cc
stratum/hal/lib/bcm/bcm_serdes_db_manager_test.cc
stratum/hal/lib/bcm/bcm_serdes_db_manager.cc
stratum/hal/lib/bcm/bcm_switch_test.cc
stratum/hal/lib/bcm/bcm_switch.cc
stratum/hal/lib/bcm/bcm_tunnel_manager_test.cc
stratum/hal/lib/bcm/bcm_tunnel_manager.cc
stratum/hal/lib/bcm/bcm_udf_manager.cc
stratum/hal/lib/bcm/bcm.proto
stratum/hal/lib/bcm/macros_test.cc
stratum/hal/lib/bcm/pipeline_processor_test.cc
stratum/hal/lib/bcm/pipeline_processor.cc
stratum/hal/lib/bcm/sdk/bcm_diag_shell.cc
stratum/hal/lib/bcm/sdk/bcm_sdk_wrapper.cc
stratum/hal/lib/bcm/sdklt/bcm_diag_shell.cc
stratum/hal/lib/bcm/sdklt/bcm_sdk_wrapper.cc
stratum/hal/lib/bcm/test_main.cc
stratum/hal/lib/bcm/utils_test.cc
stratum/hal/lib/bcm/utils.cc
stratum/hal/lib/bmv2/bmv2_chassis_manager.cc
stratum/hal/lib/bmv2/bmv2_switch.cc
stratum/hal/lib/common/admin_service_test.cc
stratum/hal/lib/common/admin_service.cc
stratum/hal/lib/common/admin_utils.cc
stratum/hal/lib/common/certificate_management_service_test.cc
stratum/hal/lib/common/certificate_management_service.cc
stratum/hal/lib/common/common.proto
stratum/hal/lib/common/config_monitoring_service_test.cc
stratum/hal/lib/common/config_monitoring_service.cc
stratum/hal/lib/common/diag_service_test.cc
stratum/hal/lib/common/diag_service.cc
stratum/hal/lib/common/error_buffer_test.cc
stratum/hal/lib/common/error_buffer.cc
stratum/hal/lib/common/file_service_test.cc
stratum/hal/lib/common/file_service.cc
stratum/hal/lib/common/gnmi_publisher_test.cc
stratum/hal/lib/common/gnmi_publisher.cc
stratum/hal/lib/common/hal_test.cc
stratum/hal/lib/common/hal.cc
stratum/hal/lib/common/openconfig_converter_test.cc
stratum/hal/lib/common/openconfig_converter.cc
stratum/hal/lib/common/p4_service_test.cc
stratum/hal/lib/common/p4_service.cc
stratum/hal/lib/common/test_main.cc
stratum/hal/lib/common/utils_test.cc
stratum/hal/lib/common/utils.cc
stratum/hal/lib/common/yang_parse_tree_paths.cc
stratum/hal/lib/common/yang_parse_tree_test.cc
stratum/hal/lib/common/yang_parse_tree.cc
stratum/hal/lib/dummy/dummy_box.cc
stratum/hal/lib/dummy/dummy_chassis_mgr.cc
stratum/hal/lib/dummy/dummy_global_vars.cc
stratum/hal/lib/dummy/dummy_node.cc
stratum/hal/lib/dummy/dummy_switch.cc
stratum/hal/lib/dummy/dummy_test.proto
stratum/hal/lib/np4intel/np4_chassis_manager_test.cc
stratum/hal/lib/np4intel/np4_chassis_manager.cc
stratum/hal/lib/np4intel/np4_switch.cc
stratum/hal/lib/np4intel/test_main.cc
stratum/hal/lib/p4/p4_action_mapper_test.cc
stratum/hal/lib/p4/p4_action_mapper.cc
stratum/hal/lib/p4/p4_config_verifier_test.cc
stratum/hal/lib/p4/p4_config_verifier.cc
stratum/hal/lib/p4/p4_info_manager_test.cc
stratum/hal/lib/p4/p4_info_manager.cc
stratum/hal/lib/p4/p4_match_key_test.cc
stratum/hal/lib/p4/p4_match_key.cc
stratum/hal/lib/p4/p4_static_entry_mapper_test.cc
stratum/hal/lib/p4/p4_static_entry_mapper.cc
stratum/hal/lib/p4/p4_table_mapper_test.cc
stratum/hal/lib/p4/p4_table_mapper.cc
stratum/hal/lib/p4/p4_write_request_differ_test.cc
stratum/hal/lib/p4/p4_write_request_differ.cc
stratum/hal/lib/p4/utils_test.cc
stratum/hal/lib/p4/utils.cc
stratum/hal/lib/phal/adapter.cc
stratum/hal/lib/phal/attribute_database_test.cc
stratum/hal/lib/phal/attribute_database.cc
stratum/hal/lib/phal/attribute_group_mock.cc
stratum/hal/lib/phal/attribute_group_test.cc
stratum/hal/lib/phal/attribute_group.cc
stratum/hal/lib/phal/datasource_mock.cc
stratum/hal/lib/phal/datasource.cc
stratum/hal/lib/phal/dummy_threadpool.cc
stratum/hal/lib/phal/fixed_layout_datasource_test.cc
stratum/hal/lib/phal/fixed_layout_datasource.cc
stratum/hal/lib/phal/onlp/onlp_cli.cc
stratum/hal/lib/phal/onlp/onlp_event_handler_test.cc
stratum/hal/lib/phal/onlp/onlp_event_handler.cc
stratum/hal/lib/phal/onlp/onlp_fan_datasource_test.cc
stratum/hal/lib/phal/onlp/onlp_fan_datasource.cc
stratum/hal/lib/phal/onlp/onlp_led_datasource_test.cc
stratum/hal/lib/phal/onlp/onlp_led_datasource.cc
stratum/hal/lib/phal/onlp/onlp_phal_cli.cc
stratum/hal/lib/phal/onlp/onlp_phal_test.cc
stratum/hal/lib/phal/onlp/onlp_phal.cc
stratum/hal/lib/phal/onlp/onlp_psu_datasource_test.cc
stratum/hal/lib/phal/onlp/onlp_psu_datasource.cc
stratum/hal/lib/phal/onlp/onlp_sfp_configurator_test.cc
stratum/hal/lib/phal/onlp/onlp_sfp_configurator.cc
stratum/hal/lib/phal/onlp/onlp_sfp_datasource_test.cc
stratum/hal/lib/phal/onlp/onlp_sfp_datasource.cc
stratum/hal/lib/phal/onlp/onlp_switch_configurator_test.cc
stratum/hal/lib/phal/onlp/onlp_switch_configurator.cc
stratum/hal/lib/phal/onlp/onlp_thermal_datasource_test.cc
stratum/hal/lib/phal/onlp/onlp_thermal_datasource.cc
stratum/hal/lib/phal/onlp/onlp_wrapper.cc
stratum/hal/lib/phal/optics_adapter_test.cc
stratum/hal/lib/phal/optics_adapter.cc
stratum/hal/lib/phal/phal_cli.cc
stratum/hal/lib/phal/phal_sim.cc
stratum/hal/lib/phal/phal_test.cc
stratum/hal/lib/phal/phal.cc
stratum/hal/lib/phal/phaldb_service_test.cc
stratum/hal/lib/phal/phaldb_service.cc
stratum/hal/lib/phal/reader_writer_datasource_test.cc
stratum/hal/lib/phal/regex_datasource_test.cc
stratum/hal/lib/phal/regex_datasource.cc
stratum/hal/lib/phal/sfp_adapter_test.cc
stratum/hal/lib/phal/sfp_adapter.cc
stratum/hal/lib/phal/system_fake.cc
stratum/hal/lib/phal/system_real.cc
stratum/hal/lib/phal/tai/tai_optics_datasource_test.cc
stratum/hal/lib/phal/tai/tai_optics_datasource.cc
stratum/hal/lib/phal/tai/tai_phal_test.cc
stratum/hal/lib/phal/tai/tai_phal.cc
stratum/hal/lib/phal/tai/tai_switch_configurator_test.cc
stratum/hal/lib/phal/tai/tai_switch_configurator.cc
stratum/hal/lib/phal/tai/taish_client.cc
stratum/hal/lib/phal/udev_event_handler_test.cc
stratum/hal/lib/phal/udev_event_handler.cc
stratum/hal/lib/phal/udev.cc
stratum/hal/lib/pi/pi_node.cc
stratum/hal/stub/embedded/main.cc
stratum/lib/channel/channel_test.cc
stratum/lib/channel/channel.cc
stratum/lib/channel/test_main.cc
stratum/lib/libcproxy/libcwrapper.cc
stratum/lib/libcproxy/passthrough_proxy.cc
stratum/lib/macros_test.cc
stratum/lib/p4runtime/p4runtime_session.cc
stratum/lib/security/auth_policy_checker_test.cc
stratum/lib/security/auth_policy_checker.cc
stratum/lib/security/certificate_test.cc
stratum/lib/security/certificate.cc
stratum/lib/security/credentials_manager_test.cc
stratum/lib/security/credentials_manager.cc
stratum/lib/security/test_main.cc
stratum/lib/statemachine/example_state_machine.cc
stratum/lib/statemachine/state_machine_test.cc
stratum/lib/test_main.cc
stratum/lib/test_utils/p4_proto_builders.cc
stratum/lib/timer_daemon_test.cc
stratum/lib/timer_daemon.cc
stratum/lib/utils_test.cc
stratum/lib/utils.cc
stratum/p4c_backends/fpm/bcm/bcm_target_info.cc
stratum/p4c_backends/fpm/meta_key_mapper.cc
stratum/p4c_backends/fpm/parser_decoder.h
stratum/p4c_backends/fpm/parser_decoder.cc
stratum/p4c_backends/fpm/parser_decoder_test.cc
stratum/p4c_backends/fpm/target_info.cc
stratum/p4c_backends/test/test_p4c_main.cc
stratum/p4c_backends/test/test_target_info.cc
stratum/portage/dummy_main.cc
stratum/procmon/procmon_main.cc
stratum/procmon/procmon_service_impl.cc
stratum/procmon/procmon_test.cc
stratum/procmon/procmon.cc
stratum/procmon/procmon.proto
stratum/public/lib/error_test.cc
stratum/public/lib/error.cc
stratum/public/lib/test_main.cc
stratum/testing/protos/p4info_parse_test.cc
stratum/testing/scenarios/test_main.cc
stratum/testing/tests/bcm_sim_test_fixture.cc
stratum/testing/tests/bcm_sim_test.cc
stratum/testing/tests/test_main.cc
stratum/tools/gnmi/gnmi_cli.cc
stratum/tools/p4_pipeline_pusher/p4_pipeline_pusher.cc
stratum/tools/stratum_replay/stratum_replay.cc
\0
EOF

echo -e "$KNOWN_FILES\n$CHANGED_FILES\n$PROTO_FILES\n$HEADER_FILES" | sort -u | xargs -t -n1 clang-format --style=file -i

# Report which files need to be fixed.
git update-index --refresh
