#!/bin/bash
# Copyright 2020-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0

set -ex

# Files in this branch that are different from main.
CHANGED_FILES=$(git diff --name-only --diff-filter=d origin/main -- '*.h' '*.cc')

# All proto files.
PROTO_FILES=$(git ls-files "*.proto")

# All header files.
HEADER_FILES=$(git ls-files "*.h")

# List of files that are already formatted.
read -r -d '\0' KNOWN_FILES << EOF
stratum/glue/gtl/map_util_test.cc
stratum/glue/gtl/map_util.h
stratum/glue/gtl/source_location.h
stratum/glue/gtl/stl_util.h
stratum/glue/init_google.h
stratum/glue/integral_types.h
stratum/glue/logging.cc
stratum/glue/logging.h
stratum/glue/net_util/absl_test.cc
stratum/glue/net_util/bits_test.cc
stratum/glue/net_util/bits.cc
stratum/glue/net_util/bits.h
stratum/glue/net_util/ipaddress_test.cc
stratum/glue/net_util/ipaddress.cc
stratum/glue/net_util/ipaddress.h
stratum/glue/net_util/ports.cc
stratum/glue/net_util/ports.h
stratum/glue/platform.h
stratum/glue/stamping.cc
stratum/glue/stamping.h
stratum/glue/status/canonical_errors.cc
stratum/glue/status/canonical_errors.h
stratum/glue/status/posix_error_space_test.cc
stratum/glue/status/posix_error_space.cc
stratum/glue/status/posix_error_space.h
stratum/glue/status/status_macros.cc
stratum/glue/status/status_macros.h
stratum/glue/status/status_test_util_test.cc
stratum/glue/status/status_test_util.cc
stratum/glue/status/status_test_util.h
stratum/glue/status/status_test.cc
stratum/glue/status/status.cc
stratum/glue/status/status.h
stratum/glue/status/statusor_test.cc
stratum/glue/status/statusor.cc
stratum/glue/status/statusor.h
stratum/hal/bin/barefoot/bf_pipeline_builder.cc
stratum/hal/bin/barefoot/main_bfrt.cc
stratum/hal/bin/barefoot/main.cc
stratum/hal/bin/bcm/sim/main.cc
stratum/hal/bin/bcm/standalone/main.cc
stratum/hal/bin/bmv2/main.cc
stratum/hal/bin/dummy/dummy_cli.cc
stratum/hal/bin/dummy/main.cc
stratum/hal/bin/np4intel/main.cc
stratum/hal/config/chassis_config_migrator.cc
stratum/hal/config/config_validator_main.cc
stratum/hal/lib/barefoot/bf_chassis_manager_mock.h
stratum/hal/lib/barefoot/bf_chassis_manager_test.cc
stratum/hal/lib/barefoot/bf_chassis_manager.cc
stratum/hal/lib/barefoot/bf_chassis_manager.h
stratum/hal/lib/barefoot/bf_pipeline_utils_test.cc
stratum/hal/lib/barefoot/bf_pipeline_utils.cc
stratum/hal/lib/barefoot/bf_pipeline_utils.h
stratum/hal/lib/barefoot/bf_sde_interface.h
stratum/hal/lib/barefoot/bf_sde_mock.h
stratum/hal/lib/barefoot/bf_sde_wrapper.cc
stratum/hal/lib/barefoot/bf_sde_wrapper.h
stratum/hal/lib/barefoot/bf_switch.cc
stratum/hal/lib/barefoot/bf_switch.h
stratum/hal/lib/barefoot/bfrt_constants.h
stratum/hal/lib/barefoot/bfrt_counter_manager_mock.h
stratum/hal/lib/barefoot/bfrt_counter_manager_test.cc
stratum/hal/lib/barefoot/bfrt_counter_manager.cc
stratum/hal/lib/barefoot/bfrt_counter_manager.h
stratum/hal/lib/barefoot/bfrt_id_mapper.cc
stratum/hal/lib/barefoot/bfrt_id_mapper.h
stratum/hal/lib/barefoot/bfrt_node_mock.h
stratum/hal/lib/barefoot/bfrt_node_test.cc
stratum/hal/lib/barefoot/bfrt_node.cc
stratum/hal/lib/barefoot/bfrt_node.h
stratum/hal/lib/barefoot/bfrt_packetio_manager_mock.h
stratum/hal/lib/barefoot/bfrt_packetio_manager_test.cc
stratum/hal/lib/barefoot/bfrt_packetio_manager.cc
stratum/hal/lib/barefoot/bfrt_packetio_manager.h
stratum/hal/lib/barefoot/bfrt_pre_manager_mock.h
stratum/hal/lib/barefoot/bfrt_pre_manager_test.cc
stratum/hal/lib/barefoot/bfrt_pre_manager.cc
stratum/hal/lib/barefoot/bfrt_pre_manager.h
stratum/hal/lib/barefoot/bfrt_switch_test.cc
stratum/hal/lib/barefoot/bfrt_switch.cc
stratum/hal/lib/barefoot/bfrt_switch.h
stratum/hal/lib/barefoot/bfrt_table_manager_mock.h
stratum/hal/lib/barefoot/bfrt_table_manager_test.cc
stratum/hal/lib/barefoot/bfrt_table_manager.cc
stratum/hal/lib/barefoot/bfrt_table_manager.h
stratum/hal/lib/barefoot/macros.h
stratum/hal/lib/barefoot/test_main.cc
stratum/hal/lib/barefoot/utils_test.cc
stratum/hal/lib/barefoot/utils.cc
stratum/hal/lib/barefoot/utils.h
stratum/hal/lib/bcm/acl_table_test.cc
stratum/hal/lib/bcm/acl_table.cc
stratum/hal/lib/bcm/acl_table.h
stratum/hal/lib/bcm/bcm_acl_manager_mock.h
stratum/hal/lib/bcm/bcm_acl_manager.cc
stratum/hal/lib/bcm/bcm_acl_manager.h
stratum/hal/lib/bcm/bcm_chassis_manager_mock.h
stratum/hal/lib/bcm/bcm_chassis_manager_test.cc
stratum/hal/lib/bcm/bcm_chassis_manager.cc
stratum/hal/lib/bcm/bcm_chassis_manager.h
stratum/hal/lib/bcm/bcm_chassis_ro_interface.h
stratum/hal/lib/bcm/bcm_chassis_ro_mock.h
stratum/hal/lib/bcm/bcm_diag_shell.h
stratum/hal/lib/bcm/bcm_flow_table_test.cc
stratum/hal/lib/bcm/bcm_flow_table.h
stratum/hal/lib/bcm/bcm_global_vars.cc
stratum/hal/lib/bcm/bcm_global_vars.h
stratum/hal/lib/bcm/bcm_l2_manager_mock.h
stratum/hal/lib/bcm/bcm_l2_manager_test.cc
stratum/hal/lib/bcm/bcm_l2_manager.cc
stratum/hal/lib/bcm/bcm_l2_manager.h
stratum/hal/lib/bcm/bcm_l3_manager_mock.h
stratum/hal/lib/bcm/bcm_l3_manager_test.cc
stratum/hal/lib/bcm/bcm_l3_manager.cc
stratum/hal/lib/bcm/bcm_l3_manager.h
stratum/hal/lib/bcm/bcm_node_mock.h
stratum/hal/lib/bcm/bcm_node_test.cc
stratum/hal/lib/bcm/bcm_node.cc
stratum/hal/lib/bcm/bcm_node.h
stratum/hal/lib/bcm/bcm_packetio_manager_mock.h
stratum/hal/lib/bcm/bcm_packetio_manager_test.cc
stratum/hal/lib/bcm/bcm_packetio_manager.cc
stratum/hal/lib/bcm/bcm_packetio_manager.h
stratum/hal/lib/bcm/bcm_sdk_interface.h
stratum/hal/lib/bcm/bcm_sdk_mock.h
stratum/hal/lib/bcm/bcm_sdk_sim.cc
stratum/hal/lib/bcm/bcm_sdk_sim.h
stratum/hal/lib/bcm/bcm_serdes_db_manager_mock.h
stratum/hal/lib/bcm/bcm_serdes_db_manager_test.cc
stratum/hal/lib/bcm/bcm_serdes_db_manager.cc
stratum/hal/lib/bcm/bcm_serdes_db_manager.h
stratum/hal/lib/bcm/bcm_switch_test.cc
stratum/hal/lib/bcm/bcm_switch.cc
stratum/hal/lib/bcm/bcm_switch.h
stratum/hal/lib/bcm/bcm_table_manager_mock.h
stratum/hal/lib/bcm/bcm_table_manager.h
stratum/hal/lib/bcm/bcm_tunnel_manager_mock.h
stratum/hal/lib/bcm/bcm_tunnel_manager_test.cc
stratum/hal/lib/bcm/bcm_tunnel_manager.cc
stratum/hal/lib/bcm/bcm_tunnel_manager.h
stratum/hal/lib/bcm/bcm_udf_manager.cc
stratum/hal/lib/bcm/bcm_udf_manager.h
stratum/hal/lib/bcm/bcm.proto
stratum/hal/lib/bcm/constants.h
stratum/hal/lib/bcm/macros_test.cc
stratum/hal/lib/bcm/pipeline_processor_test.cc
stratum/hal/lib/bcm/pipeline_processor.cc
stratum/hal/lib/bcm/pipeline_processor.h
stratum/hal/lib/bcm/sdk_build_undef.h
stratum/hal/lib/bcm/sdk/bcm_diag_shell.cc
stratum/hal/lib/bcm/sdk/bcm_sdk_wrapper.cc
stratum/hal/lib/bcm/sdk/bcm_sdk_wrapper.h
stratum/hal/lib/bcm/sdk/macros.h
stratum/hal/lib/bcm/sdk/sdk_build_flags.h
stratum/hal/lib/bcm/sdklt/bcm_diag_shell.cc
stratum/hal/lib/bcm/sdklt/bcm_sdk_wrapper.cc
stratum/hal/lib/bcm/sdklt/bcm_sdk_wrapper.h
stratum/hal/lib/bcm/sdklt/macros.h
stratum/hal/lib/bcm/test_main.cc
stratum/hal/lib/bcm/utils_test.cc
stratum/hal/lib/bcm/utils.cc
stratum/hal/lib/bcm/utils.h
stratum/hal/lib/bmv2/bmv2_chassis_manager.cc
stratum/hal/lib/bmv2/bmv2_chassis_manager.h
stratum/hal/lib/bmv2/bmv2_switch.cc
stratum/hal/lib/bmv2/bmv2_switch.h
stratum/hal/lib/common/admin_service_test.cc
stratum/hal/lib/common/admin_service.cc
stratum/hal/lib/common/admin_service.h
stratum/hal/lib/common/admin_utils_interface.h
stratum/hal/lib/common/admin_utils_mock.h
stratum/hal/lib/common/admin_utils.cc
stratum/hal/lib/common/certificate_management_service_test.cc
stratum/hal/lib/common/certificate_management_service.cc
stratum/hal/lib/common/certificate_management_service.h
stratum/hal/lib/common/channel_writer_wrapper.h
stratum/hal/lib/common/client_sync_reader_writer.h
stratum/hal/lib/common/common.proto
stratum/hal/lib/common/config_monitoring_service_test.cc
stratum/hal/lib/common/config_monitoring_service.cc
stratum/hal/lib/common/config_monitoring_service.h
stratum/hal/lib/common/constants.h
stratum/hal/lib/common/diag_service_test.cc
stratum/hal/lib/common/diag_service.cc
stratum/hal/lib/common/diag_service.h
stratum/hal/lib/common/error_buffer_test.cc
stratum/hal/lib/common/error_buffer.cc
stratum/hal/lib/common/error_buffer.h
stratum/hal/lib/common/file_service_test.cc
stratum/hal/lib/common/file_service.cc
stratum/hal/lib/common/file_service.h
stratum/hal/lib/common/gnmi_events.h
stratum/hal/lib/common/gnmi_publisher_mock.h
stratum/hal/lib/common/gnmi_publisher_test.cc
stratum/hal/lib/common/gnmi_publisher.cc
stratum/hal/lib/common/gnmi_publisher.h
stratum/hal/lib/common/hal_test.cc
stratum/hal/lib/common/hal.cc
stratum/hal/lib/common/hal.h
stratum/hal/lib/common/openconfig_converter_test.cc
stratum/hal/lib/common/openconfig_converter.cc
stratum/hal/lib/common/openconfig_converter.h
stratum/hal/lib/common/p4_service_test.cc
stratum/hal/lib/common/p4_service.cc
stratum/hal/lib/common/p4_service.h
stratum/hal/lib/common/phal_interface.h
stratum/hal/lib/common/phal_mock.h
stratum/hal/lib/common/proto_oneof_writer_wrapper.h
stratum/hal/lib/common/server_writer_wrapper.h
stratum/hal/lib/common/subscribe_reader_writer_mock.h
stratum/hal/lib/common/switch_interface.h
stratum/hal/lib/common/switch_mock.h
stratum/hal/lib/common/test_main.cc
stratum/hal/lib/common/utils_test.cc
stratum/hal/lib/common/utils.cc
stratum/hal/lib/common/utils.h
stratum/hal/lib/common/writer_interface.h
stratum/hal/lib/common/writer_mock.h
stratum/hal/lib/common/yang_parse_tree_mock.h
stratum/hal/lib/common/yang_parse_tree_paths.cc
stratum/hal/lib/common/yang_parse_tree_paths.h
stratum/hal/lib/common/yang_parse_tree_test.cc
stratum/hal/lib/common/yang_parse_tree.cc
stratum/hal/lib/common/yang_parse_tree.h
stratum/hal/lib/dummy/dummy_box.cc
stratum/hal/lib/dummy/dummy_box.h
stratum/hal/lib/dummy/dummy_chassis_mgr.cc
stratum/hal/lib/dummy/dummy_chassis_mgr.h
stratum/hal/lib/dummy/dummy_global_vars.cc
stratum/hal/lib/dummy/dummy_global_vars.h
stratum/hal/lib/dummy/dummy_node.cc
stratum/hal/lib/dummy/dummy_node.h
stratum/hal/lib/dummy/dummy_switch.cc
stratum/hal/lib/dummy/dummy_switch.h
stratum/hal/lib/dummy/dummy_test.proto
stratum/hal/lib/np4intel/np4_chassis_manager_test.cc
stratum/hal/lib/np4intel/np4_chassis_manager.cc
stratum/hal/lib/np4intel/np4_chassis_manager.h
stratum/hal/lib/np4intel/np4_switch.cc
stratum/hal/lib/np4intel/np4_switch.h
stratum/hal/lib/np4intel/test_main.cc
stratum/hal/lib/p4/p4_action_mapper_test.cc
stratum/hal/lib/p4/p4_action_mapper.cc
stratum/hal/lib/p4/p4_action_mapper.h
stratum/hal/lib/p4/p4_config_verifier_test.cc
stratum/hal/lib/p4/p4_config_verifier.cc
stratum/hal/lib/p4/p4_config_verifier.h
stratum/hal/lib/p4/p4_info_manager_mock.h
stratum/hal/lib/p4/p4_info_manager_test.cc
stratum/hal/lib/p4/p4_info_manager.cc
stratum/hal/lib/p4/p4_info_manager.h
stratum/hal/lib/p4/p4_match_key_test.cc
stratum/hal/lib/p4/p4_match_key.cc
stratum/hal/lib/p4/p4_match_key.h
stratum/hal/lib/p4/p4_static_entry_mapper_mock.h
stratum/hal/lib/p4/p4_static_entry_mapper_test.cc
stratum/hal/lib/p4/p4_static_entry_mapper.cc
stratum/hal/lib/p4/p4_static_entry_mapper.h
stratum/hal/lib/p4/p4_table_mapper_mock.h
stratum/hal/lib/p4/p4_table_mapper_test.cc
stratum/hal/lib/p4/p4_table_mapper.cc
stratum/hal/lib/p4/p4_table_mapper.h
stratum/hal/lib/p4/p4_write_request_differ_test.cc
stratum/hal/lib/p4/p4_write_request_differ.cc
stratum/hal/lib/p4/p4_write_request_differ.h
stratum/hal/lib/p4/utils_test.cc
stratum/hal/lib/p4/utils.cc
stratum/hal/lib/p4/utils.h
stratum/hal/lib/phal/adapter.cc
stratum/hal/lib/phal/adapter.h
stratum/hal/lib/phal/attribute_database_interface.h
stratum/hal/lib/phal/attribute_database_mock.h
stratum/hal/lib/phal/attribute_database_test.cc
stratum/hal/lib/phal/attribute_database.cc
stratum/hal/lib/phal/attribute_database.h
stratum/hal/lib/phal/attribute_group_mock.cc
stratum/hal/lib/phal/attribute_group_mock.h
stratum/hal/lib/phal/attribute_group_test.cc
stratum/hal/lib/phal/attribute_group.cc
stratum/hal/lib/phal/attribute_group.h
stratum/hal/lib/phal/buffer_tools.h
stratum/hal/lib/phal/datasource_mock.cc
stratum/hal/lib/phal/datasource_mock.h
stratum/hal/lib/phal/datasource.cc
stratum/hal/lib/phal/datasource.h
stratum/hal/lib/phal/dummy_threadpool.cc
stratum/hal/lib/phal/dummy_threadpool.h
stratum/hal/lib/phal/filepath_stringsource.h
stratum/hal/lib/phal/fixed_layout_datasource_test.cc
stratum/hal/lib/phal/fixed_layout_datasource.cc
stratum/hal/lib/phal/fixed_layout_datasource.h
stratum/hal/lib/phal/fixed_stringsource.h
stratum/hal/lib/phal/managed_attribute_mock.h
stratum/hal/lib/phal/managed_attribute.h
stratum/hal/lib/phal/onlp/onlp_cli.cc
stratum/hal/lib/phal/onlp/onlp_event_handler_mock.h
stratum/hal/lib/phal/onlp/onlp_event_handler_test.cc
stratum/hal/lib/phal/onlp/onlp_event_handler.cc
stratum/hal/lib/phal/onlp/onlp_event_handler.h
stratum/hal/lib/phal/onlp/onlp_fan_datasource_test.cc
stratum/hal/lib/phal/onlp/onlp_fan_datasource.cc
stratum/hal/lib/phal/onlp/onlp_fan_datasource.h
stratum/hal/lib/phal/onlp/onlp_led_datasource_test.cc
stratum/hal/lib/phal/onlp/onlp_led_datasource.cc
stratum/hal/lib/phal/onlp/onlp_led_datasource.h
stratum/hal/lib/phal/onlp/onlp_phal_cli.cc
stratum/hal/lib/phal/onlp/onlp_phal_interface.h
stratum/hal/lib/phal/onlp/onlp_phal_mock.h
stratum/hal/lib/phal/onlp/onlp_phal_test.cc
stratum/hal/lib/phal/onlp/onlp_phal.cc
stratum/hal/lib/phal/onlp/onlp_phal.h
stratum/hal/lib/phal/onlp/onlp_psu_datasource_test.cc
stratum/hal/lib/phal/onlp/onlp_psu_datasource.cc
stratum/hal/lib/phal/onlp/onlp_psu_datasource.h
stratum/hal/lib/phal/onlp/onlp_sfp_configurator_test.cc
stratum/hal/lib/phal/onlp/onlp_sfp_configurator.cc
stratum/hal/lib/phal/onlp/onlp_sfp_configurator.h
stratum/hal/lib/phal/onlp/onlp_sfp_datasource_test.cc
stratum/hal/lib/phal/onlp/onlp_sfp_datasource.cc
stratum/hal/lib/phal/onlp/onlp_sfp_datasource.h
stratum/hal/lib/phal/onlp/onlp_switch_configurator_test.cc
stratum/hal/lib/phal/onlp/onlp_switch_configurator.cc
stratum/hal/lib/phal/onlp/onlp_switch_configurator.h
stratum/hal/lib/phal/onlp/onlp_thermal_datasource_test.cc
stratum/hal/lib/phal/onlp/onlp_thermal_datasource.cc
stratum/hal/lib/phal/onlp/onlp_thermal_datasource.h
stratum/hal/lib/phal/onlp/onlp_wrapper_mock.h
stratum/hal/lib/phal/onlp/onlp_wrapper.cc
stratum/hal/lib/phal/onlp/onlp_wrapper.h
stratum/hal/lib/phal/optics_adapter_test.cc
stratum/hal/lib/phal/optics_adapter.cc
stratum/hal/lib/phal/optics_adapter.h
stratum/hal/lib/phal/phal_backend_interface.h
stratum/hal/lib/phal/phal_cli.cc
stratum/hal/lib/phal/phal_sim.cc
stratum/hal/lib/phal/phal_sim.h
stratum/hal/lib/phal/phal_test.cc
stratum/hal/lib/phal/phal.cc
stratum/hal/lib/phal/phal.h
stratum/hal/lib/phal/phaldb_service_test.cc
stratum/hal/lib/phal/phaldb_service.cc
stratum/hal/lib/phal/phaldb_service.h
stratum/hal/lib/phal/reader_writer_datasource_test.cc
stratum/hal/lib/phal/reader_writer_datasource.h
stratum/hal/lib/phal/regex_datasource_test.cc
stratum/hal/lib/phal/regex_datasource.cc
stratum/hal/lib/phal/regex_datasource.h
stratum/hal/lib/phal/sfp_adapter_test.cc
stratum/hal/lib/phal/sfp_adapter.cc
stratum/hal/lib/phal/sfp_adapter.h
stratum/hal/lib/phal/sfp_configurator.h
stratum/hal/lib/phal/stringsource_interface.h
stratum/hal/lib/phal/switch_configurator_interface.h
stratum/hal/lib/phal/system_fake.cc
stratum/hal/lib/phal/system_fake.h
stratum/hal/lib/phal/system_interface_mock.h
stratum/hal/lib/phal/system_interface.h
stratum/hal/lib/phal/system_real.cc
stratum/hal/lib/phal/system_real.h
stratum/hal/lib/phal/tai/tai_interface_mock.h
stratum/hal/lib/phal/tai/tai_interface.h
stratum/hal/lib/phal/tai/tai_optics_datasource_test.cc
stratum/hal/lib/phal/tai/tai_optics_datasource.cc
stratum/hal/lib/phal/tai/tai_optics_datasource.h
stratum/hal/lib/phal/tai/tai_phal_test.cc
stratum/hal/lib/phal/tai/tai_phal.cc
stratum/hal/lib/phal/tai/tai_phal.h
stratum/hal/lib/phal/tai/tai_switch_configurator_test.cc
stratum/hal/lib/phal/tai/tai_switch_configurator.cc
stratum/hal/lib/phal/tai/tai_switch_configurator.h
stratum/hal/lib/phal/tai/taish_client.cc
stratum/hal/lib/phal/tai/taish_client.h
stratum/hal/lib/phal/test_util.h
stratum/hal/lib/phal/threadpool_interface_mock.h
stratum/hal/lib/phal/threadpool_interface.h
stratum/hal/lib/phal/udev_event_handler_mock.h
stratum/hal/lib/phal/udev_event_handler_test.cc
stratum/hal/lib/phal/udev_event_handler.cc
stratum/hal/lib/phal/udev_event_handler.h
stratum/hal/lib/phal/udev_interface.h
stratum/hal/lib/phal/udev_mock.h
stratum/hal/lib/phal/udev.cc
stratum/hal/lib/phal/udev.h
stratum/hal/lib/pi/pi_node.cc
stratum/hal/lib/pi/pi_node.h
stratum/hal/stub/embedded/main.cc
stratum/lib/channel/channel_internal.h
stratum/lib/channel/channel_mock.h
stratum/lib/channel/channel_test.cc
stratum/lib/channel/channel.cc
stratum/lib/channel/channel.h
stratum/lib/channel/test_main.cc
stratum/lib/constants.h
stratum/lib/libcproxy/libcwrapper.cc
stratum/lib/libcproxy/libcwrapper.h
stratum/lib/libcproxy/passthrough_proxy.cc
stratum/lib/libcproxy/passthrough_proxy.h
stratum/lib/macros_test.cc
stratum/lib/macros.h
stratum/lib/p4runtime/p4runtime_session.cc
stratum/lib/p4runtime/p4runtime_session.h
stratum/lib/security/auth_policy_checker_mock.h
stratum/lib/security/auth_policy_checker_test.cc
stratum/lib/security/auth_policy_checker.cc
stratum/lib/security/auth_policy_checker.h
stratum/lib/security/certificate_test.cc
stratum/lib/security/certificate.cc
stratum/lib/security/certificate.h
stratum/lib/security/credentials_manager_mock.h
stratum/lib/security/credentials_manager_test.cc
stratum/lib/security/credentials_manager.cc
stratum/lib/security/credentials_manager.h
stratum/lib/security/test_main.cc
stratum/lib/statemachine/example_state_machine.cc
stratum/lib/statemachine/example_state_machine.h
stratum/lib/statemachine/state_machine_test.cc
stratum/lib/statemachine/state_machine.h
stratum/lib/test_main.cc
stratum/lib/test_utils/matchers.h
stratum/lib/test_utils/p4_proto_builders.cc
stratum/lib/test_utils/p4_proto_builders.h
stratum/lib/timer_daemon_test.cc
stratum/lib/timer_daemon.cc
stratum/lib/timer_daemon.h
stratum/lib/utils_test.cc
stratum/lib/utils.cc
stratum/lib/utils.h
stratum/p4c_backends/common/backend_extension_interface.h
stratum/p4c_backends/common/backend_extension_mock.h
stratum/p4c_backends/common/backend_pass_manager.h
stratum/p4c_backends/common/midend_interface.h
stratum/p4c_backends/common/midend_p4c_open.h
stratum/p4c_backends/common/p4c_front_mid_interface.h
stratum/p4c_backends/common/p4c_front_mid_mock.h
stratum/p4c_backends/common/p4c_front_mid_real.h
stratum/p4c_backends/common/program_inspector.h
stratum/p4c_backends/fpm/action_decoder.h
stratum/p4c_backends/fpm/annotation_mapper.h
stratum/p4c_backends/fpm/bcm/bcm_target_info.cc
stratum/p4c_backends/fpm/bcm/bcm_target_info.h
stratum/p4c_backends/fpm/bcm/bcm_tunnel_optimizer.h
stratum/p4c_backends/fpm/condition_inspector.h
stratum/p4c_backends/fpm/control_inspector.h
stratum/p4c_backends/fpm/expression_inspector.h
stratum/p4c_backends/fpm/field_cross_reference.h
stratum/p4c_backends/fpm/field_decoder.h
stratum/p4c_backends/fpm/field_name_inspector.h
stratum/p4c_backends/fpm/header_path_inspector.h
stratum/p4c_backends/fpm/header_valid_inspector.h
stratum/p4c_backends/fpm/hidden_static_mapper.h
stratum/p4c_backends/fpm/hidden_table_mapper.h
stratum/p4c_backends/fpm/hit_assign_mapper.h
stratum/p4c_backends/fpm/internal_action.h
stratum/p4c_backends/fpm/meta_key_mapper.cc
stratum/p4c_backends/fpm/meta_key_mapper.h
stratum/p4c_backends/fpm/meter_color_mapper.h
stratum/p4c_backends/fpm/method_call_decoder.h
stratum/p4c_backends/fpm/midend.h
stratum/p4c_backends/fpm/parser_decoder.h
stratum/p4c_backends/fpm/parser_field_mapper.h
stratum/p4c_backends/fpm/parser_value_set_mapper.h
stratum/p4c_backends/fpm/pipeline_block_passes.h
stratum/p4c_backends/fpm/pipeline_intra_block_passes.h
stratum/p4c_backends/fpm/pipeline_optimizer.h
stratum/p4c_backends/fpm/simple_hit_inspector.h
stratum/p4c_backends/fpm/slice_cross_reference.h
stratum/p4c_backends/fpm/switch_case_decoder_mock.h
stratum/p4c_backends/fpm/switch_case_decoder.h
stratum/p4c_backends/fpm/switch_p4c_backend.h
stratum/p4c_backends/fpm/table_hit_inspector.h
stratum/p4c_backends/fpm/table_map_generator_mock.h
stratum/p4c_backends/fpm/table_map_generator.h
stratum/p4c_backends/fpm/table_type_mapper.h
stratum/p4c_backends/fpm/target_info_mock.h
stratum/p4c_backends/fpm/target_info.cc
stratum/p4c_backends/fpm/target_info.h
stratum/p4c_backends/fpm/tunnel_optimizer_interface.h
stratum/p4c_backends/fpm/tunnel_optimizer_mock.h
stratum/p4c_backends/fpm/tunnel_type_mapper.h
stratum/p4c_backends/fpm/utils.h
stratum/p4c_backends/test/ir_test_helpers.h
stratum/p4c_backends/test/test_inspectors.h
stratum/p4c_backends/test/test_p4c_main.cc
stratum/p4c_backends/test/test_target_info.cc
stratum/p4c_backends/test/test_target_info.h
stratum/portage/dummy_main.cc
stratum/procmon/procmon_main.cc
stratum/procmon/procmon_service_impl.cc
stratum/procmon/procmon_service_impl.h
stratum/procmon/procmon_test.cc
stratum/procmon/procmon.cc
stratum/procmon/procmon.h
stratum/procmon/procmon.proto
stratum/public/lib/error_test.cc
stratum/public/lib/error.cc
stratum/public/lib/error.h
stratum/public/lib/test_main.cc
stratum/testing/protos/p4info_parse_test.cc
stratum/testing/scenarios/test_main.cc
stratum/testing/tests/bcm_sim_test_fixture.cc
stratum/testing/tests/bcm_sim_test_fixture.h
stratum/testing/tests/bcm_sim_test.cc
stratum/testing/tests/test_main.cc
stratum/tools/gnmi/gnmi_cli.cc
stratum/tools/p4_pipeline_pusher/p4_pipeline_pusher.cc
stratum/tools/stratum_replay/stratum_replay.cc
\0
EOF

echo -e "$KNOWN_FILES\n$CHANGED_FILES\n$PROTO_FILES\n$HEADER_FILES" | sort -u | xargs -t -n1 clang-format --style=file -i

# Report which files need to be fixed.
git update-index --refresh
