#!/bin/bash

STRATUM_BUILDER_IMAGE="stratumproject/build:build"
# if Dockerfile.build changed...
STRATUM_BUILDER_IMAGE="stratumproject/build:ci-${CIRCLE_PR_NUMBER}"
sed "s/##STRATUM_BUILDER_IMAGE##/${STRATUM_BUILDER_IMAGE}/g" config_template.yml > generated_config.yml
sed -i "s/##PUBLISH_DOCKER_BUILD##/- publish-docker-build/g" generated_config.yml
