#!/bin/bash
CURRENT_DIR="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
STRATUM_BUILDER_IMAGE="stratumproject/build:build"
PUBLISH_DOCKER_BUILD=""
# if Dockerfile.build changed...
git diff main HEAD --stat | grep Dockerfile.build &> /dev/null
BUILDER_IMG_CHANGED=$?
if [[ $BUILDER_IMG_CHANGED != 0 ]]; then
STRATUM_BUILDER_IMAGE="stratumproject/build:ci-${CIRCLE_BRANCH}"
PUBLISH_DOCKER_BUILD="- publish-docker-build"
fi
CONFIG_FILE=$(mktemp)
sed "s@##STRATUM_BUILDER_IMAGE##@${STRATUM_BUILDER_IMAGE}@g" "$CURRENT_DIR/config_template.yml" > "$CONFIG_FILE"
if [[ $BUILDER_IMG_CHANGED != 0 ]]; then
sed -i "s@##PUBLISH_DOCKER_BUILD##@$PUBLISH_DOCKER_BUILD@g" "$CONFIG_FILE"
fi
cat "$CONFIG_FILE"
