# Copyright 2018 Google LLC
# Copyright 2018-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0

licenses(["notice"])  # Apache v2

package(
    #default_hdrs_check = "strict",
    default_visibility = ["//visibility:public"],
)

exports_files([
    "build_defs.bzl",
])

cc_library(
    name = "dummy",
)

cc_library(
    name = "dummy_with_main",
    srcs = ["dummy_main.cc"],
)
