# All IR definition files for backends in the Stratum repo must be exported
# to compile with the p4lang/p4c repo's IR definitions as one monolithic IR.
exports_files(
    [
        "stratum_ir.def",
    ],
    visibility = ["//visibility:public"],
)
