# Copyright 2018 Google LLC
# Copyright 2018-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0

licenses(["notice"])  # Apache v2

# All IR definition files for backends in the Stratum repo must be exported
# to compile with the p4lang/p4c repo's IR definitions as one monolithic IR.
exports_files(
    [
        "stratum_fpm_ir.def",
    ],
    visibility = ["//visibility:public"],
)
